// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM1JTTHIL79Xm89jVV8dFq0rZEFY94pP0',
    appId: '1:1018086533747:web:718b1eaa6dd106572f5806',
    messagingSenderId: '1018086533747',
    projectId: 'chatapp-48105',
    authDomain: 'chatapp-48105.firebaseapp.com',
    storageBucket: 'chatapp-48105.appspot.com',
    measurementId: 'G-W4MDY8FQGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_k93hO1dvBBaB_cc6ahClWuA70by34Xk',
    appId: '1:1018086533747:android:2e43c7e2311034442f5806',
    messagingSenderId: '1018086533747',
    projectId: 'chatapp-48105',
    storageBucket: 'chatapp-48105.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOtpCb-fsTVkPFUcQtSYxA-4DOvXtQbFM',
    appId: '1:1018086533747:ios:029c69c8dcd7b0da2f5806',
    messagingSenderId: '1018086533747',
    projectId: 'chatapp-48105',
    storageBucket: 'chatapp-48105.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOtpCb-fsTVkPFUcQtSYxA-4DOvXtQbFM',
    appId: '1:1018086533747:ios:7b96b2876711166a2f5806',
    messagingSenderId: '1018086533747',
    projectId: 'chatapp-48105',
    storageBucket: 'chatapp-48105.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
